# Generated by Django 5.1.4 on 2025-02-25 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
        ('doctor', '0002_reviewmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmodel',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.availabletimemodel'),
        ),
    ]
